# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-16 21:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='messanger',
            new_name='message',
        ),
    ]
